print("Enter first number:-")
a=int(input())
print("Enter second number:-")
b=int(input())
print("Addition is",a+b)
print("Subtraction is",a-b)
print("Multiplicatio is",a*b)
print("Divison is",a/b)
print("Modulus is",a%b)
